version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:8080"
    volumes:
      - .:/app
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 10s
      timeout: 30s
      retries: 3

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
    volumes:
      - .:/var/www/html
    ports:
      - "5432:5432"
